"use client";
import { useEffect, useRef, useState } from "react";
import { Maximize2, Minus, Plus } from "lucide-react";
import { renderToCanvas } from "@/features/editor/image-processing";
import { useEditorStore } from "@/features/editor/store";
export function CanvasStage(){const canvasRef=useRef<HTMLCanvasElement>(null);const image=useEditorStore(s=>s.image);const adjustments=useEditorStore(s=>s.adjustments);const showOriginal=useEditorStore(s=>s.showOriginal);const zoom=useEditorStore(s=>s.zoom);const panX=useEditorStore(s=>s.panX);const panY=useEditorStore(s=>s.panY);const setZoom=useEditorStore(s=>s.setZoom);const setPan=useEditorStore(s=>s.setPan);const [rendering,setRendering]=useState(false);const drag=useRef<{x:number;y:number;px:number;py:number}|null>(null);
 useEffect(()=>{if(!image||!canvasRef.current)return;let cancelled=false;setRendering(true);const img=new Image();img.onload=()=>{if(cancelled||!canvasRef.current)return;requestAnimationFrame(()=>{try{const effective=showOriginal?Object.fromEntries(Object.keys(adjustments).map(k=>[k,0])) as typeof adjustments:adjustments;renderToCanvas(img,img.naturalWidth,img.naturalHeight,canvasRef.current!,effective); }finally{setRendering(false);}})};img.onerror=()=>setRendering(false);img.src=image.objectUrl;return()=>{cancelled=true;};},[image,adjustments,showOriginal]);
 if(!image)return null;
 return <div className="stage"><div className="canvas-viewport" onWheel={e=>{e.preventDefault();setZoom(zoom+(e.deltaY<0?.1:-.1));}} onPointerDown={e=>{drag.current={x:e.clientX,y:e.clientY,px:panX,py:panY};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(!drag.current)return;setPan(drag.current.px+e.clientX-drag.current.x,drag.current.py+e.clientY-drag.current.y);}} onPointerUp={()=>{drag.current=null;}}><canvas ref={canvasRef} style={{transform:`translate(${panX}px, ${panY}px) scale(${zoom})`}} aria-label="Edited image preview"/>{rendering&&<span className="render-badge">Rendering preview…</span>}</div><div className="zoom-bar"><button onClick={()=>setZoom(zoom-.25)} aria-label="Zoom out"><Minus size={15}/></button><output>{Math.round(zoom*100)}%</output><button onClick={()=>setZoom(zoom+.25)} aria-label="Zoom in"><Plus size={15}/></button><button onClick={()=>{setZoom(1);setPan(0,0)}} aria-label="Fit image"><Maximize2 size={15}/></button></div></div>}
