"use client";
import { useEffect, useState } from "react";
import { useEditorStore } from "@/features/editor/store";
import { useStudioStore } from "@/features/studio/store";
import { createLayer } from "@/features/render/layers";
import { parseCube, type ChannelCurves } from "@/features/editor/color-tools";
import { layersSchema } from "@/features/projects/backup";
import { getRecord, putRecord } from "@/lib/local-records";
import type { EditorLayer } from "@/features/editor/types";
import { IMAGE_ACCEPT, normalizeImage } from "@/features/editor/import-image";
import { T, useT } from "@/features/i18n/text";
import { TEMPLATES, templateSnapshot } from "@/features/editor/templates";
type SavedLook={id:string;name:string;layer:EditorLayer};
export function CreativeTools() {
 const s=useEditorStore(), t=useT();const [message,setMessage]=useState("");const [looks,setLooks]=useState<SavedLook[]>([]);
 const layer=s.layers.find(l=>l.id===s.activeLayerId);const disabled=!s.image||s.layers.length>=20;
 useEffect(()=>{getRecord<SavedLook[]>("color:looks").then(v=>setLooks(v??[])).catch(()=>setMessage("Could not load saved looks"));},[]);
 const add=(layer:EditorLayer)=>{s.addLayer(layer);useStudioStore.getState().setCompareMode("off");};
 function portrait(kind:"skin"|"shine"|"light"|"clone"|"heal") {
  const layer=createLayer();layer.name=t({skin:"Skin texture",shine:"Reduce shine",light:"Face lighting",clone:"Clone blemishes",heal:"Healing brush"}[kind]);layer.adjustments=kind==="skin"?{texture:-8,noiseReduction:10}:kind==="shine"?{highlights:-35,whites:-10}:kind==="light"?{exposure:.2,shadows:12}:{};
  layer.opacity=.65;layer.mask={...layer.mask,kind:(kind==="clone"||kind==="heal")?"all":"radial",radius:.25,feather:.8};
  if(kind==="clone"||kind==="heal") {layer.retouchMode=kind==="heal"?"heal":"clone";layer.retouch=[];layer.x=.45;layer.y=.45;}
  add(layer);s.setMaskEditing(true);
 }
 return <div className="creative-tools"><label className="button"><T text="Add image layer"/><input aria-label="Add image layer" hidden disabled={disabled} type="file" accept={IMAGE_ACCEPT} onChange={async e=>{const file=e.target.files?.[0];e.target.value="";if(!file)return;const original=s.image;try{const normalized=await normalizeImage(file);const bitmap=await createImageBitmap(normalized);try{if(bitmap.width*bitmap.height>60_000_000)throw new Error("Image exceeds 60 megapixels");const canvas=document.createElement("canvas");const frame=document.querySelector<HTMLCanvasElement>('[aria-label="Edited image preview"]');const fw=frame?.width||original?.width||bitmap.width,fh=frame?.height||original?.height||bitmap.height;const factor=Math.min(1,2000/Math.max(fw,fh));canvas.width=Math.max(1,Math.round(fw*factor));canvas.height=Math.max(1,Math.round(fh*factor));const fit=Math.min(canvas.width/bitmap.width,canvas.height/bitmap.height);const dw=bitmap.width*fit,dh=bitmap.height*fit;canvas.getContext("2d")!.drawImage(bitmap,(canvas.width-dw)/2,(canvas.height-dh)/2,dw,dh);const layer=createLayer("raster");layer.name=file.name.slice(0,100);layer.dataUrl=canvas.toDataURL("image/png");layer.replaceBase=false;layer.transform={x:0,y:0,scale:.5,rotation:0};canvas.width=canvas.height=0;if(useEditorStore.getState().image!==original)throw new Error("The image changed. Try again.");add(layer);setMessage("Image layer added. Up to 2000 px; use Transform to position it.");}finally{bitmap.close();}}catch(e){setMessage((e as Error).message);}}}/></label><details><summary><T text="Templates" /></summary><p className="control-note"><T text="Templates set a crop and editable text layers. Undo restores your previous layout." /></p><div className="creative-grid">{TEMPLATES.map(template=><button disabled={disabled} key={template.id} onClick={()=>{try{s.restoreSnapshot(templateSnapshot(s.committed,template.id));setMessage("Template applied. Edit the text in Layers.");}catch(e){setMessage((e as Error).message);}}}><T text={template.name}/><small>{template.ratio}</small></button>)}</div></details>
 <details><summary><T text="Portrait retouch" /></summary><p className="control-note"><T text="Manual local retouch. Position the mask on the face and adjust opacity to retain texture." /></p><div className="creative-grid">{(["skin","shine","light","clone","heal"] as const).map(kind=><button disabled={disabled} key={kind} onClick={()=>portrait(kind)}><T text={{skin:"Skin texture",shine:"Reduce shine",light:"Face lighting",clone:"Clone blemishes",heal:"Healing brush"}[kind]}/></button>)}</div>{layer?.retouch && <div className="layer-controls"><p><T text="Set a clean source with the sliders, then tap blemishes on the image. Each spot can be undone." /></p>{(["x","y"] as const).map(key=><label key={key}>{t("Clone source")} {key.toUpperCase()}<input aria-label={`Clone source ${key}`} type="range" min=".01" max=".99" step=".005" value={layer[key]??.45} onChange={e=>s.updateLayer(layer.id,{[key]:+e.target.value})}/></label>)}<label><T text="Brush size"/><input aria-label="Clone radius" type="range" min=".003" max=".08" step=".001" value={s.brushRadius} onChange={e=>s.setBrush(+e.target.value,false)}/></label><button onClick={()=>s.setMaskEditing(!s.maskEditing)}><T text={s.maskEditing?"Finish retouch":"Retouch on image"}/></button><button onClick={()=>s.updateLayer(layer.id,{retouch:[]})}><T text="Clear spots"/></button><output className="retouch-count" aria-label="Retouch spots">{layer.retouch.length}</output></div>}</details>
 <details><summary><T text="Pro color · RGB & LUT"/></summary><button disabled={disabled} onClick={()=>{const layer=createLayer();layer.name="RGB curves";layer.adjustments={};layer.channelCurves={red:[0,.25,.5,.75,1],green:[0,.25,.5,.75,1],blue:[0,.25,.5,.75,1]};add(layer);}}><T text="Add RGB curves"/></button><label className="button"><T text="Import .cube LUT"/><input hidden disabled={disabled} type="file" accept=".cube" onChange={async e=>{const file=e.target.files?.[0];e.target.value="";if(!file)return;try{if(file.size>5_000_000)throw new Error("LUT exceeds 5 MB");const lut=parseCube(await file.text());const next=createLayer();next.name=lut.title;next.adjustments={};next.lut=lut;add(next);setMessage("LUT imported. Use layer opacity to control intensity.");}catch(e){setMessage((e as Error).message);}}}/></label>
 {layer?.channelCurves && <div className="channel-curves">{(["red","green","blue"] as const).map(channel=><fieldset key={channel}><legend><T text={channel}/></legend><svg viewBox="0 0 100 100" role="img" aria-label={`${channel} curve`}><path d="M0 100L100 0" stroke="gray" fill="none"/><polyline fill="none" stroke={channel} strokeWidth="2" points={layer.channelCurves![channel].map((n,i)=>`${i*25},${100-n*100}`).join(" ")}/></svg>{layer.channelCurves![channel].map((value,i)=><label key={i}>{i*25}%<input type="range" aria-label={`${channel} curve ${i*25}%`} min="0" max="1" step=".01" value={value} onChange={e=>{const curves=structuredClone(layer.channelCurves) as ChannelCurves;curves[channel][i]=+e.target.value;s.updateLayer(layer.id,{channelCurves:curves});}}/></label>)}</fieldset>)}</div>}
 <button disabled={!layer||(!layer.lut&&!layer.channelCurves)||looks.length>=30} onClick={async()=>{if(!layer)return;const name=window.prompt(t("Save color recipe"),layer.name)?.trim().slice(0,100);if(!name)return;const next=[...looks,{id:crypto.randomUUID(),name,layer}];try{await putRecord("color:looks",next);setLooks(next);setMessage("Color recipe saved");}catch{setMessage("Could not save color recipe");}}}><T text="Save color recipe"/></button>
 {looks.map(look=><div className="saved-color-row" key={look.id}><button disabled={disabled} onClick={()=>{try{const [parsed]=layersSchema.parse([look.layer]);add({...parsed,id:crypto.randomUUID(),name:look.name});}catch{setMessage("Invalid saved recipe");}}}>{look.name}</button><button aria-label={`${t("Delete")} ${look.name}`} onClick={async()=>{const next=looks.filter(l=>l.id!==look.id);try{await putRecord("color:looks",next);setLooks(next);}catch{setMessage("Could not save color recipe");}}}>×</button></div>)}</details>{message&&<p role="status"><T text={message}/></p>}</div>;
}
