"use client";
import { useEffect, useState } from "react";
import { Download, Redo2, Save, Undo2 } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { AdjustmentPanel } from "./adjustment-panel";
import { AiPanel } from "./ai-panel";
import { CanvasStage } from "./canvas-stage";
import { ImportZone } from "./import-zone";
import { PresetStrip } from "./preset-strip";
import { useEditorStore } from "@/features/editor/store";
import { renderToCanvas } from "@/features/editor/image-processing";
export function EditorWorkspace(){const image=useEditorStore(s=>s.image);const adjustments=useEditorStore(s=>s.adjustments);const undo=useEditorStore(s=>s.undo);const redo=useEditorStore(s=>s.redo);const past=useEditorStore(s=>s.past);const future=useEditorStore(s=>s.future);const toggle=useEditorStore(s=>s.toggleOriginal);const showOriginal=useEditorStore(s=>s.showOriginal);const [tab,setTab]=useState<"adjust"|"ai">("adjust");const [notice,setNotice]=useState("");
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="z"){e.preventDefault();e.shiftKey?redo():undo();}if(e.key==="\\")toggle();};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key);},[redo,undo,toggle]);
 async function exportImage(type:"image/png"|"image/jpeg"){if(!image)return;setNotice("Rendering full export…");try{const img=new Image();img.src=image.objectUrl;await img.decode();const canvas=document.createElement("canvas");renderToCanvas(img,img.naturalWidth,img.naturalHeight,canvas,adjustments,6000);const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,type,type==="image/jpeg"?.92:undefined));if(!blob)throw new Error("Export encoder unavailable");const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=`${image.name.replace(/\.[^.]+$/,"")}-lumaforge.${type==="image/png"?"png":"jpg"}`;link.click();setNotice("Export complete");setTimeout(()=>setNotice(""),2200);}catch(e){setNotice(e instanceof Error?e.message:"Export failed");}}
 return <AppShell><header className="editor-topbar"><div><span className="kicker">Project</span><strong>{image?.name??"Untitled edit"}</strong></div><div className="top-actions"><button className="icon-button" onClick={undo} disabled={!past.length} title="Undo"><Undo2/></button><button className="icon-button" onClick={redo} disabled={!future.length} title="Redo"><Redo2/></button><button className={showOriginal?"button active":"button"} onPointerDown={()=>toggle(true)} onPointerUp={()=>toggle(false)} onPointerLeave={()=>toggle(false)}>Hold original</button><button className="button" onClick={()=>setNotice("Adjustments autosaved locally")}><Save size={16}/> Saved locally</button><button className="button primary" disabled={!image} onClick={()=>void exportImage("image/jpeg")}><Download size={16}/> Export JPG</button></div></header>{notice&&<div className="toast" role="status">{notice}</div>}<div className="editor-grid"><main className="editor-main">{image?<CanvasStage/>:<ImportZone/>}{image&&<PresetStrip/>}</main><aside className="right-panel"><div className="panel-tabs"><button className={tab==="adjust"?"active":""} onClick={()=>setTab("adjust")}>Adjust</button><button className={tab==="ai"?"active":""} onClick={()=>setTab("ai")}>AI Plan</button></div>{tab==="adjust"?<AdjustmentPanel/>:<AiPanel/>}</aside></div></AppShell>}
