"use client";
import { RefineTools } from "./refine-tools";
import { CreativeTools } from "./creative-tools";
import { T, useT } from "@/features/i18n/text";

import { Eye, EyeOff, Plus, Trash2, Type, ArrowUp, ArrowDown } from "lucide-react";
import { useEditorStore } from "@/features/editor/store";
import { useStudioStore } from "@/features/studio/store";
import { createLayer } from "@/features/render/layers";
import type { LayerMask } from "@/features/editor/types";
export function LayerPanel() {
  const t = useT();
  const state = useEditorStore();
  const selected = state.layers.find((l) => l.id === state.activeLayerId);
  const update = selected ? (patch: Partial<typeof selected>) => state.updateLayer(selected.id, patch) : () => {};
  function add(kind: "text" | "adjustment") { state.addLayer(createLayer(kind)); }
  return <div className="layer-panel"><CreativeTools /><div className="layer-actions"><button disabled={!state.image || state.layers.length >= 20} onClick={() => add("adjustment")}><Plus size={14} /> <T text={"Adjustment"} /> </button><button disabled={!state.image || state.layers.length >= 20} onClick={() => add("text")}><Type size={14} /> <T text={"Text"} /> </button></div><p className="control-note"> <T text={"Layers render bottom to top. Masks follow the cropped image coordinates."} /> </p><div className="layer-list">{[...state.layers].reverse().map((layer) => <div className={layer.id === state.activeLayerId ? "layer-row selected" : "layer-row"} key={layer.id}><button aria-label={`Toggle ${layer.name}`} aria-pressed={layer.visible} onClick={() => state.updateLayer(layer.id, { visible: !layer.visible })}>{layer.visible ? <Eye size={14} /> : <EyeOff size={14} />}</button><button className="layer-name" onClick={() => state.setActiveLayer(layer.id)}>{layer.name}<small>{layer.kind} · {Math.round(layer.opacity * 100)}%</small></button><button aria-label="Move layer up" onClick={() => state.moveLayer(layer.id, 1)}><ArrowUp size={12} /></button><button aria-label="Move layer down" onClick={() => state.moveLayer(layer.id, -1)}><ArrowDown size={12} /></button><button aria-label={`Delete ${layer.name}`} onClick={() => state.removeLayer(layer.id)}><Trash2 size={13} /></button></div>)}</div>{selected && <div className="layer-controls"><RefineTools key={selected.id} layer={selected}/><label> <T text={"Layer name"} /> <input value={selected.name} maxLength={100} onChange={(e) => update({ name: e.target.value })} /></label><label> <T text={"Opacity"} /> <output>{Math.round(selected.opacity * 100)}%</output><input type="range" min="0" max="1" step=".01" value={selected.opacity} onChange={(e) => update({ opacity: +e.target.value })} /></label>{selected.kind === "adjustment" && <>{(["exposure", "contrast", "shadows", "highlights", "saturation", "temperature"] as const).map((key) => <label key={key}>{key}<input type="range" aria-label={`Layer ${key}`} min={key === "exposure" ? -2 : -100} max={key === "exposure" ? 2 : 100} step={key === "exposure" ? .05 : 1} value={selected.adjustments[key] ?? 0} onChange={(e) => update({ adjustments: { ...selected.adjustments, [key]: +e.target.value } })} /></label>)}</>}{selected.kind === "text" && <><label> <T text={"Text"} /> <input value={selected.text ?? ""} maxLength={500} onChange={(e) => update({ text: e.target.value })} /></label><label> <T text={"Text color"} /> <input type="color" value={selected.color ?? "#ffffff"} onChange={(e) => update({ color: e.target.value })} /></label>{(["fontSize", "x", "y"] as const).map((key) => <label key={key}>{key}<input type="range" min={key === "fontSize" ? .005 : 0} max={key === "fontSize" ? .3 : 1} step=".005" value={selected[key] ?? .5} onChange={(e) => update({ [key]: +e.target.value })} /></label>)}</>}
      <label> <T text={"Mask"} /> <select aria-label="Mask" value={selected.mask.kind} onChange={(e) => update({ mask: { ...selected.mask, kind: e.target.value as LayerMask["kind"] } })}><option value="all">{t("Whole image")}</option><option value="radial">{t("Radial")}</option><option value="linear">{t("Linear")}</option><option value="brush">{t("Brush")}</option>{selected.mask.dataUrl && <option value="image">{t("AI mask")}</option>}</select></label>{selected.mask.kind !== "all" && <><label><input type="checkbox" checked={selected.mask.invert} onChange={(e) => update({ mask: { ...selected.mask, invert: e.target.checked } })} /> <T text={"Invert mask"} /> </label>{selected.mask.kind !== "brush" && (["x", "y", "radius", "feather"] as const).map((key) => <label key={key}>{key}<input type="range" min=".01" max="1" step=".01" value={selected.mask[key]} onChange={(e) => update({ mask: { ...selected.mask, [key]: +e.target.value } })} /></label>)}{selected.mask.kind === "brush" && <><label> <T text={"Brush size"} /> <input type="range" min=".005" max=".2" step=".005" value={state.brushRadius} onChange={(e) => state.setBrush(+e.target.value, state.brushErase)} /></label><label><input type="checkbox" checked={state.brushErase} onChange={(e) => state.setBrush(state.brushRadius, e.target.checked)} /> <T text={"Erase mask"} /> </label><button onClick={() => update({ mask: { ...selected.mask, strokes: [], dataUrl: undefined } })}> <T text={"Clear strokes"} /> </button></>}<button aria-pressed={state.maskEditing} onClick={() => { state.setMaskEditing(!state.maskEditing); useStudioStore.getState().setCompareMode("off"); }}>{t(state.maskEditing ? "Finish mask" : "Edit mask on image")}</button></>}
    </div>}{!state.layers.length && <p className="control-note"> <T text={"Add an adjustment layer to edit part of your image, or add text."} /> </p>}</div>;
}
