import { notFound } from "next/navigation";
import Link from "next/link";
import { AppShell } from "@/components/app-shell";
import { ArrowRight, CircleCheck, Construction, ShieldAlert } from "lucide-react";
const sections={
 "ai-studio":{title:"AI Studio",status:"PARTIAL",summary:"Transparent local edit-plan generation is available inside the Editor. Real vision and generative providers are not connected.",ready:["Prompt validation","Explainable adjustment plans","Apply plan to non-destructive state"],next:["Image scene analysis","Real provider adapter","Job queue and credit ledger"]},
 beauty:{title:"Beauty Studio",status:"PLANNED",summary:"Identity-preserving portrait tools require segmentation and landmark models. No hidden face geometry modification is active.",ready:["Product requirements","Identity protection rules"],next:["Face/skin masks","Natural texture pipeline","Multi-person controls"]},
 batch:{title:"Batch Edit",status:"PLANNED",summary:"Album-wide synchronization is not yet implemented. The current editor handles one image at a time.",ready:["Workflow specification","Preset recipes"],next:["Multi-file queue","Pause/resume","Per-image overrides"]},
 gallery:{title:"Gallery",status:"PLANNED",summary:"Asset management requires IndexedDB or Supabase persistence. No demo assets are shown as real files.",ready:["Information architecture"],next:["Local asset index","Metadata filters","Trash and restore"]},
 projects:{title:"Projects",status:"PARTIAL",summary:"Adjustment recipes autosave locally. Durable named projects and cloud sync are not connected.",ready:["Local editor persistence","Non-destructive recipes"],next:["Project CRUD","Asset ownership","Cloud sync status"]},
 presets:{title:"Presets",status:"FUNCTIONAL",summary:"Five built-in presets apply real adjustment state in the editor and participate in undo/redo.",ready:["Live application","Undo/redo","Preset descriptions"],next:["User preset save","Import/export XMP","Collections"]},
 community:{title:"Community",status:"NOT STARTED",summary:"No fake social feed is included. Community requires authentication, moderation and privacy controls.",ready:["Requirements"],next:["Profiles and posts","Permissions","Reporting and moderation"]},
 marketplace:{title:"Marketplace",status:"NOT STARTED",summary:"No fake checkout or purchase success state is included.",ready:["Requirements"],next:["Catalog schema","Verified payment flow","Entitlements and downloads"]},
 settings:{title:"Settings",status:"PARTIAL",summary:"Editor state persists locally. Full account, privacy, storage and performance settings remain planned.",ready:["Local autosave","Dark-first accessible UI"],next:["Processing mode controls","Data deletion","Reduced motion and high contrast"]}
} as const;
export default async function SectionPage({params}:{params:Promise<{section:string}>}){const {section}=await params;const data=sections[section as keyof typeof sections];if(!data)notFound();return <AppShell><main className="module-page"><div className="module-head"><div><span className="kicker">Module status</span><h1>{data.title}</h1><p>{data.summary}</p></div><span className={`status-pill ${data.status.toLowerCase().replace(" ","-")}`}>{data.status}</span></div><div className="module-grid"><section className="module-card"><CircleCheck/><h2>Available now</h2><ul>{data.ready.map(item=><li key={item}>{item}</li>)}</ul></section><section className="module-card"><Construction/><h2>Required next</h2><ul>{data.next.map(item=><li key={item}>{item}</li>)}</ul></section><section className="module-card truth"><ShieldAlert/><h2>No fake completion</h2><p>This page reports actual module state. Unconnected backend, AI, payment and collaboration features are not represented as working.</p></section></div><Link className="button primary" href="/editor">Open functional editor <ArrowRight size={16}/></Link></main></AppShell>}
