import {test,expect,type Page} from '@playwright/test';
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAABAAAAAMCAIAAADkharWAAAAF0lEQVR4nGOsCDjBQApgIkn1qIYRpAEAsVkBqEXr8uYAAAAASUVORK5CYII=','base64');
test.beforeEach(async({page})=>{await page.addInitScript(()=>localStorage.setItem('lumaforge-preferences-v1',JSON.stringify({state:{language:'en'},version:0})));});
async function imported(page:Page){await page.goto('/editor?tool=layers');await page.locator('input[type=file]').first().setInputFiles({name:'pro.png',mimeType:'image/png',buffer:png});await expect(page.getByLabel('Edited image preview')).toBeVisible();}
test('layer grouping, locking and duplicating survive recovery',async({page,isMobile})=>{await imported(page);await page.locator('.layer-actions').getByRole('button',{name:'Text',exact:true}).click();await page.getByLabel('Layer group',{exact:true}).fill('Portrait');await page.getByRole('button',{name:'Lock Text',exact:true}).click();await expect(page.getByLabel('Layer group',{exact:true})).toBeDisabled();await page.getByRole('button',{name:'Duplicate Text',exact:true}).click();await expect(page.locator('.layer-row')).toHaveCount(2);await expect(page.getByLabel('Layer group',{exact:true})).toHaveValue('Portrait');await expect(page.locator('.draft-status')).toContainText('Draft saved');await page.reload();if(isMobile)await page.getByTitle('Collapse inspector').click();await page.getByRole('button',{name:'Recover draft',exact:true}).first().click();if(isMobile)await page.getByTitle('Open Editing Inspector').click();await expect(page.locator('.layer-row')).toHaveCount(2);await expect(page.getByRole('button',{name:'Unlock Text',exact:true})).toBeVisible();});
test('export reports native-size limits',async({page,isMobile})=>{await imported(page);if(isMobile)await page.getByTitle('Collapse inspector').click();await page.getByRole('button',{name:'Save project',exact:true}).click();await expect(page.locator('.professional-toast')).toContainText('saved locally');await page.goto('/export-center');await expect(page.getByLabel('Export preflight')).toContainText('keeps native size');});

test('pixel color picking, clipping and projective geometry change the displayed image',async({page,isMobile})=>{
 await page.goto('/editor?tool=layers');await page.locator('input[type=file]').first().setInputFiles({name:'red.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAACAAAAAYCAIAAAAUMWhjAAAAJElEQVR4nGP8z0BbwERj80ctGLVg1IJRC0YtGLVg1IJRC6gEAPHIAS8Wxt4fAAAAAElFTkSuQmCC','base64')});await expect(page.getByLabel('Edited image preview')).toBeVisible();
 await page.locator('[data-section="color"] .inspector-section-toggle').click();await page.getByRole('button',{name:'Pick color from image',exact:true}).click();if(isMobile)await page.getByTitle('Collapse inspector').click();await page.getByLabel('Edited image preview').click();if(isMobile)await page.getByTitle('Open Editing Inspector').click();await expect(page.locator('.selected-color')).toHaveText('Red');
 await page.getByTitle('Toggle highlight clipping warning').click();await expect.poll(()=>page.getByLabel('Pixel clipping overlay').evaluate(n=>(n as HTMLCanvasElement).getContext('2d')!.getImageData(0,0,1,1).data[3])).toBe(180);
 await page.locator('[data-section="geometry"] .inspector-section-toggle').click();await page.getByLabel('Horizontal perspective',{exact:true}).press('End');await expect.poll(()=>page.getByLabel('Edited image preview').evaluate(n=>{const c=n as HTMLCanvasElement;return c.getContext('2d')!.getImageData(c.width-1,0,1,1).data[3];})).toBe(0);
});

test('named branches retain ancestry and compare independently',async({page,isMobile})=>{
 await imported(page);if(isMobile)await page.getByTitle('Collapse inspector').click();await page.getByRole('button',{name:'Save project',exact:true}).click();await expect(page.locator('.professional-toast')).toContainText('saved locally');if(isMobile)await page.getByTitle('Open Editing Inspector').click();
 const toggle=page.locator('[data-section="versions"] .inspector-section-toggle');if(await toggle.getAttribute('aria-expanded')!=='true')await toggle.click();await page.getByLabel('Snapshot name',{exact:true}).fill('Base');await page.getByRole('button',{name:'Create snapshot',exact:true}).click();await expect(page.locator('.version-row')).toHaveCount(1);
 await page.getByTitle('Branch version',{exact:true}).click();await expect(page.getByLabel('Snapshot name',{exact:true})).toHaveValue('Base Branch');await page.getByLabel('Snapshot name',{exact:true}).fill('Warm');await page.getByRole('button',{name:'Create snapshot',exact:true}).click();await expect(page.locator('.version-row')).toHaveCount(2);await page.getByLabel('Compare Base',{exact:true}).check();await page.getByLabel('Compare Warm',{exact:true}).check();await expect(page.getByLabel('Version comparison').locator('figure')).toHaveCount(2);await expect(page.locator('.version-row').filter({hasText:'Warm'})).toContainText('Branch from: Base');
});
