"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import { Copy, Download, Pencil, Search, Trash2, Upload } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { DEFAULT_ADJUSTMENTS, PRESETS } from "@/features/editor/defaults";
import type { Adjustments, UserPreset } from "@/features/editor/types";
import { deleteUserPreset, duplicateUserPreset, listUserPresets, renameUserPreset, saveUserPreset } from "@/lib/idb";

const knownKeys = new Set(Object.keys(DEFAULT_ADJUSTMENTS));
function downloadJson(preset:UserPreset){const blob=new Blob([JSON.stringify({version:1,type:"lumaforge-preset",preset},null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`${preset.name.replace(/[^a-z0-9-_]+/gi,"-")}.lumaforge.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1500);}
function parsePreset(value:unknown):UserPreset{if(!value||typeof value!=="object")throw new Error("Invalid preset file");const wrapper=value as {preset?:unknown};const raw=(wrapper.preset??value) as Partial<UserPreset>;if(!raw.adjustments||typeof raw.adjustments!=="object")throw new Error("Preset adjustments are missing");const adjustments:Partial<Adjustments>={};for(const [key,setting] of Object.entries(raw.adjustments)){if(knownKeys.has(key)&&typeof setting==="number"&&Number.isFinite(setting))(adjustments as Record<string,number>)[key]=setting;}if(!Object.keys(adjustments).length)throw new Error("Preset contains no supported adjustments");const now=new Date().toISOString();return{id:crypto.randomUUID(),name:typeof raw.name==="string"&&raw.name.trim()?raw.name.trim():"Imported Preset",description:typeof raw.description==="string"?raw.description:"Imported LumaForge recipe",createdAt:now,updatedAt:now,adjustments,scope:raw.scope==="light"||raw.scope==="color"?raw.scope:"full"};}

export function PresetLibrary(){
  const inputRef=useRef<HTMLInputElement>(null);const [custom,setCustom]=useState<UserPreset[]>([]);const [query,setQuery]=useState("");const [status,setStatus]=useState("");
  const refresh=useCallback(async()=>{try{setCustom(await listUserPresets());setStatus("");}catch(error){setStatus(error instanceof Error?error.message:"Unable to load presets");}},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void refresh(),0);return()=>window.clearTimeout(timer);},[refresh]);
  const filtered=useMemo(()=>{const term=query.trim().toLowerCase();if(!term)return custom;return custom.filter(preset=>`${preset.name} ${preset.description} ${preset.scope}`.toLowerCase().includes(term));},[custom,query]);
  async function importFile(file?:File){if(!file)return;try{if(file.size>1024*1024)throw new Error("Preset file is too large");const preset=parsePreset(JSON.parse(await file.text()));await saveUserPreset(preset);await refresh();setStatus(`Imported ${preset.name}`);}catch(error){setStatus(error instanceof Error?error.message:"Preset import failed");}}
  async function rename(preset:UserPreset){const name=window.prompt("Rename preset",preset.name)?.trim();if(!name||name===preset.name)return;try{await renameUserPreset(preset.id,name);await refresh();}catch(error){setStatus(error instanceof Error?error.message:"Rename failed");}}
  async function remove(preset:UserPreset){if(!window.confirm(`Delete preset “${preset.name}”?`))return;try{await deleteUserPreset(preset.id);await refresh();}catch(error){setStatus(error instanceof Error?error.message:"Delete failed");}}
  return <AppShell><main className="preset-page"><header className="project-heading"><div><span className="kicker">Reusable non-destructive recipes</span><h1>Presets</h1><p>Built-in looks and user presets share the editor adjustment model. JSON imports accept only known numeric adjustment keys.</p></div><Link className="button primary" href="/editor">Open editor</Link></header><div className="preset-toolbar"><label className="search-field"><Search size={16}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search personal presets"/></label><button className="button preset-import" onClick={()=>inputRef.current?.click()}><Upload size={16}/> Import JSON</button><input ref={inputRef} hidden type="file" accept="application/json,.json" onChange={event=>void importFile(event.target.files?.[0])}/></div>{status&&<p className="preset-status" role="status">{status}</p>}<h2 className="section-label">Built-in</h2><section className="preset-list">{PRESETS.map(preset=><article className="preset-library-card" key={preset.id}><header><span className={`preset-swatch ${preset.id}`}/><div><h2>{preset.name}</h2><p>{preset.description}</p></div><span className="built-in-badge">BUILT-IN</span></header><div className="preset-meta"><span>{Object.keys(preset.adjustments).length} adjustments</span></div></article>)}</section><h2 className="section-label">Personal</h2>{!filtered.length&&<div className="mini-empty">No matching personal presets. Save the current edit from the preset strip or import JSON.</div>}<section className="preset-list">{filtered.map(preset=><article className="preset-library-card" key={preset.id}><header><span className="preset-swatch custom"/><div><h2>{preset.name}</h2><p>{preset.description}</p></div></header><div className="preset-meta"><span>{preset.scope}</span><span>{Object.keys(preset.adjustments).length} adjustments</span><span>{new Date(preset.updatedAt).toLocaleDateString()}</span></div><div className="preset-actions"><button className="icon-button" title="Rename" onClick={()=>void rename(preset)}><Pencil size={15}/></button><button className="icon-button" title="Duplicate" onClick={()=>void duplicateUserPreset(preset.id).then(refresh).catch((error:unknown)=>setStatus(error instanceof Error?error.message:"Duplicate failed"))}><Copy size={15}/></button><button className="icon-button" title="Export JSON" onClick={()=>downloadJson(preset)}><Download size={15}/></button><button className="icon-button danger-button" title="Delete" onClick={()=>void remove(preset)}><Trash2 size={15}/></button></div></article>)}</section></main></AppShell>;
}
